
package scacs

import akka.actor.Actor

/**
 * Message type used to tell the master how many nodes are expected to be registered.
 *
 * @param numNodes The number of nodes the {{MasterService}} should wait to register.
 */
case class ClusterSize(numNodes: Int)

/**
 * Message type used by the {{ClusterService}} actor on each node to
 * announce itself to the {{MasterService}} actor.
 * 
 * @param hostname  The {{ClusterService}}'s host name
 * @param port      The {{ClusterService}}'s port number
 */
case class Announce(hostname: String, port: Int)

/**
 * Message type used for broadcasting node addresses.
 *
 * @param addresses a list of addresses of the remote nodes
 */
case class Nodes(addresses: List[(String, Int)])

/**
 * Message type used for starting a new actor on a remote node.
 *
 * @param clazz the class of the actor to be started
 */
case class Start(clazz: Class[_ <: Actor])


/**
 * Message type used by {{MasterService}} for submitting a task to a node,
 * when it expects to receive a tracking number for a processed data
 * item in return, rather than the actual data item.
 *
 * TODO: Variants of this which deal with data partitioning and/or shipping.
 *
 * @param host The hostname of the {{ClusterService}} to submit to.
 * @param port The port number of the {{ClusterService}} to submit to.
 * @param fun The function to distribute.
 * @param input The input data to distribute and process.
 * @trackingNumber The tracking number generated by {{MasterService}} to be used by {{ClusterService}} to locally store result.
 */
case class SubmitAt(host: String, port: Int,
                  fun: (ClusterService,Any)=>Any,
                  input: Any,
                  trackingNumber: Option[Int])

/**
 * Message type used by {{MasterService}} for submitting a task to a node,
 * when it expects to receive directly receive the processed data item in return.
 *
 * TODO: Variants of this which deal with data partitioning and/or shipping.
 *
 * @param host The hostname of the {{ClusterService}} to submit to.
 * @param port The port number of the {{ClusterService}} to submit to.
 * @param fun The function to distribute.
 * @param input The input data to distribute and process.
 * @trackingNumber The tracking number generated by {{MasterService}} to be used by {{ClusterService}} to locally store result. This is an optional. If no trackingNumber is provided, then the result is not stored locally by {{ClusterService}}.
 */
case class InvokeAt(host: String, port: Int,
                  fun: (ClusterService,Any)=>Any,
                  input: Any,
                  trackingNumber: Option[Int] = None)

